[project]
name = "comfyui-teleport"
description = "A ComfyUI extension that teleports image previews to a separate live-updating browser window."
version = "0.1.0"
license = {file = "LICENSE"}
dependencies = []

[project.urls]
Repository = "https://github.com/guansss/ComfyUI-teleport"

# Used by Comfy Registry https://comfyregistry.org
[tool.comfy]
PublisherId = "your_publisher_id" # Change this to your actual publisher ID
DisplayName = "ComfyUI Teleport"
Icon = ""
includes = ["dist/"]